export const stats = [
  {
    "MEN TYPE 1" : 36,
    "MEN TYPE 2" : 28,
    "WOMEN TYPE 1" : 18,
    "WOMEN TYPE 2" : 12,
    "MEN TYPE 1 HAIRLESS" : 2,
    "ABSENT" : 2,
    "INSPECTEUR GADGET" : 2
  },
  {
    "HTML/CSS" : 22,
    "HTML/CSS SPECIAL FOLLOWER EDITION" : 2,
    "RUBY ON RAILS" : 26,
    "JAVASCRIPT" : 24,
    "REACT" : 24,
    "BINARY" : 2
  },
  {
    "N°1" : 4,
    "N°2" : 14,
    "N°3" : 8,
    "N°4" : 14,
    "N°5" : 12,
    "N°6" : 16,
    "N°7" : 8,
    "N°8" : 10,
    "N°9" : 6,
    "NO EXPRESSION" : 4,
    "CAPTAIN MELON" : 2,
    "INSPECTEUR GADGET" : 2
  },
  {
    "N°1 SUNGLASSES" : 10,
    "N°2" : 16,
    "N°3" : 10,
    "N°3 SPECIAL GOLD EDITION" : 2,
    "N°4" : 10,
    "N°5 SKI EDITION" : 4,
    "NO GLASSES" : 48
  },
  {
    "CLASSIC" : 74,
    "SPECIAL STAFF" : 8,
    "SPECIAL CUP OF TEA" : 2,
    "SPECIAL GOLD EDITION" : 2,
    "SPECIAL INSPECTEUR GADGET" : 2,
    "SPECIAL CAPTAIN MELON" : 2,
    "SPECIAL HARRY POTTER" : 2,
    "SPECIAL BRITTANY" : 2,
    "SPECIAL ABSENT" : 2,
    "SPECIAL GREEN EDITION" : 2
  },
  {
    "REACT" : 8,
    "LINUX" : 10,
    "MUSTACHE" : 12,
    "MUSIC" : 8,
    "STACK OVERFLOW" : 8,
    "IA SKULL" : 8,
    "CODING KING" : 6,
    "GITHUB" : 10,
    "NINJA FULLSTACK" : 10,
    "STAFF" : 6,
    "GREEN SNAKE" : 2,
    "DOBBY" : 2,
    "CAPTAIN MELON" : 2,
    "POOP" : 2,
    "CATAMARAN" : 2,
    "INSPECTEUR GADGET" : 2,
    "CUP OF TEA" : 2,
    "NO STICKER" : 6
  },
  {
    "SOCIAL SMARTPHONE" : 2,
    "SPIDER" : 6,
    "CAP" : 14,
    "CHRISTMAS HAT" : 4,
    "POSTER" : 6,
    "PIN'S NO PAIN NO GAIN" : 4,
    "HEADPHONES" : 22,
    "SOMBRERO" : 6,
    "CAMERA" : 8,
    "LANTERN" : 2,
    "BATMAN MASK" : 2,
    "GADGET" : 2,
    "CAPTAIN'S CAP" : 2,
    "HARRY POTTER ACCESSORIES" : 2,
    "TOILET PAPER ROLL" : 2,
    "BRITTANY ACCESSORIES" : 2,
    "CARNAVAL MASK" : 2,
    "NO ARTICLE" : 14
  },
  {
    "PASTEL BEIGE" : 18,
    "BROWN" : 10,
    "BLUE" : 14,
    "PURPLE" : 8,
    "GREEN" : 12,
    "PURPLE RED" : 8,
    "YELLOW" : 12,
    "GRAY STAFF" : 6,
    "SPECIAL CUP OF TEA" : 2,
    "SPECIAL CAPTAIN MELON" : 2,
    "SPECIAL HARRY POTTER" : 2,
    "SPECIAL BRITTANY" : 2,
    "SPECIAL GOLD EDITION" : 2
  },
  {
    "BLACK" : 50,
    "SILVER" : 36,
    "PEARLY" : 10,
    "SPECIAL GREEN EDITION" : 2,
    "SPECIAL GOLD EDITION" : 2
  }
]